export const messageMetadata = {
	totalMessages: 134593,
	messagesByAuthor: {
		"Gary Morris": 43590,
		Mikey: 48041,
		"Nicholas Barooah": 3505,
		"Rob Croft": 32327,
		"Ian Rooney": 6749,
		"Lucy Barnes": 375,
	},
	bioByAuthor: {
		"Gary Morris": {
			summary:
				"Gary comes across as a sociable and humorous person who enjoys discussing his daily life, hobbies (especially music), and engaging in banter with friends. His style is very informal, uses a lot of slang and expressive punctuation, and often includes self-deprecating remarks.",
			contentThemes: [
				"Social Life & Plans: Gary often discusses weekend plans, nights out, drinking (sometimes humorously mentioning his gout and attempts to be booze-free), attending events like weddings, and coordinating meetups with friends.",
				"Hobbies & Interests: He frequently talks about music, including playing instruments (bass, guitar), music software, attending gigs, and his taste in music (metal, rock, sometimes expressing dislike for bands like Van Halen later in life). He also discusses films, TV shows (like Stranger Things), and occasionally gaming. Pastimes like sea fishing are also mentioned.",
				"Work & Technology: Gary shares updates about his work life, including being a contractor, meetings, job roles, working from home, and sometimes expressing boredom or frustration with work. He discusses tech purchases like TVs and sound systems.",
				"Daily Life: Topics include travel (especially trips to London, sometimes expressing dislike for the city), home life (tidying, dealing with pets), food (BBQs, takeaways, meals out, cooking), and health issues like gout or dentist visits.",
				"Banter & Observations: He engages in plenty of banter with friends, shares jokes, links, and makes observations about life, politics (like Brexit), and people.",
			],
			style: [
				"Informal & Conversational: He uses very casual language, including slang (e.g., 'Wassap monkey pluckers', 'owt', 'booze', 'ace', 'shite', 'knackered', 'chocka'), abbreviations ('coz', 'summut', 'chrimbo', 'bevvy'), and emojis/GIFs frequently.",
				"Humorous & Self-Deprecating: He often makes jokes, sometimes at his own expense (calling himself a 'twat', 'idiot'), and engages in banter with his friends. He uses humour to discuss topics like his health (gout) or difficult situations.",
				"Exclamatory & Expressive: Uses exclamation marks frequently to convey enthusiasm or other strong feelings.",
			],
		},
		Mikey: {
			summary:
				"Mikey appears as a sociable and tech-literate individual who actively engages in group conversations. He often initiates or participates in discussions about social arrangements, travel, technology (like Kodi, phones, and software), music, films, and TV shows. His communication style is informal, marked by frequent banter, teasing, and asking questions. He seems interested in trying new things (like Nandos ), traveling (Iceland ), and keeping up with technology trends and entertainment",
			contentThemes: [
				"Social Plans & Activities: Mikey frequently discusses social plans and activities, such as walking trips (Hilbre Island), holidays (Iceland, Chester races), and nights out, often asking about others' plans too.",
				"Technology: A recurring theme in Mikey's messages, particularly concerning Kodi addons (Phoenix, Zem TV, Bulldog), phones (Nexus 6P), music software (Cubase, Pro-Tools), and managing digital photos on Google Photos.",
				"Entertainment: Mikey discusses films (Eddie the Eagle, Dr. Strangelove), music (Springsteen, The Wall, Iron Maiden, criticizing others' choices), and TV shows (Game of Thrones, Walking Dead, Preacher, Robot Wars).",
				"Personal Updates: He shares updates on work (WFH), health (sore foot, feeling ill, back issues), DIY (wallpapering), and family life.",
				"Current Events: Mikey expresses opinions on current events like the Hillsborough verdict and Brexit.",
				"Food & Drink: Mikey talks about his preferences for wine, Nandos, and curry.",
			],
			style: [
				"Informal & Conversational: Mikey's writing style is very informal and conversational. He uses slang ('krap', 'soz', 'battered', 'shite'), abbreviations ('tomoz', 'yip'), and local dialect ('owt').",
				"Banter & Teasing: A key part of his style is engaging in frequent banter and teasing with his friends, often making jokes at their expense (e.g., about Gary's dancing or Rob's train food).",
				"Inquisitive: He asks a lot of questions, shares links and photos, and engages actively in group conversations.",
				"Direct & Opinionated: Mikey can be quite direct or opinionated, especially regarding music or tech.",
			],
		},
		"Rob Croft": {
			summary:
				"Rob Croft appears to be a sociable person interested in technology, films, food, and interacting with his friends. He actively participates in group chats, often discussing tech issues, making social plans, sharing observations from his daily life, and engaging in informal banter. His communication style is conversational and practical, frequently asking questions and offering suggestions, especially related to technology.",
			contentThemes: [
				"Technology: Discusses phones (like the Nexus 6P), streaming services and devices (Kodi, Amazon Prime), TV streaming quality, Google products (Photos metadata, Hangouts), computer issues (suggesting Ubuntu), and general tech troubleshooting.",
				"Social Planning: Engages in organizing nights out and social events with friends, often discussing dates and locations (like Ormskirk).",
				"Daily Life & Observations: Shares observations about everyday experiences like train journeys (complaining about first-class food), dentist visits, work trips (Manchester, London), being ill, and home life (dealing with squirrels in the loft).",
				"Entertainment: Discusses films (e.g., Steve Jobs, Batman v Superman, Martyrs), music (harmonica, comments on others' music choices), and TV shows (Robot Wars).",
				"Food: Talks about meals and restaurants (Nandos, curry places, Whoppers).",
				"Opinions & Banter: Participates in friendly banter, expresses opinions on events (like the Hillsborough verdict), and engages in general conversation with the group.",
			],
			style: [
				"Informal & Conversational: Uses casual language, slang ('mad', 'slog'), and engages in back-and-forth banter with friends.",
				"Inquisitive: Frequently asks questions to others in the group, seeking opinions or information (e.g., asking about phone features, checking if people are working).",
				"Observational: Often shares observations about his surroundings or experiences (e.g., train service, dentist waiting room).",
				"Practical: Offers suggestions and solutions, such as recommending Ubuntu for computer issues or troubleshooting Google Photos dates.",
				"Self-Correcting: Occasionally corrects his own typos (e.g., *room, *sky, *stance, *and).",
				"Uses Emojis: Uses emojis occasionally to add tone.",
			],
		},
		"Ian Rooney": {
			summary:
				"Ian Rooney's messages chronicle his life from 2016 to early 2021. He frequently discusses his social life, making plans with friends (Mike, Gary, Rob) for nights out, curries, and drinks. Family life is prominent, with mentions of his wife Helen, their children (Sam, Joel, Esme), their activities like football and school events, and family holidays to places like Cornwall, Majorca, the Lake District, and Croatia.   Work is a recurring topic, often discussed with frustration and boredom. He talks about attending conferences, dealing with work projects, and occasionally contemplates career changes.   His hobbies include music (especially playing guitar, listening to bands like The Who and Black Crowes, and attending gigs), watching films and TV shows, following football (Everton), and dealing with technology like phones, computers, and home gadgets. He also touches on DIY projects, car issues, and attempts at vegetarianism and moderating alcohol intake, often with humorous self-deprecation about his efforts and subsequent hangovers. Throughout the messages, he shares personal reflections, health updates, and opinions in an informal, conversational style. Sources and related content",
			contentThemes: [
				"Social and Personal Life: Frequent updates on social plans, holidays, family events, and activities with friends and children.",
				"Work Commentary: Regular comments about his IT job, often expressing boredom, frustration, or stress related to workload, projects, and workplace events like conferences.",
				"Hobbies and Interests: Discussions about music (listening, playing guitar, opinions on bands), technology (phones, gadgets, troubleshooting), films and TV shows, food and drink preferences, sports (especially football), and DIY projects.",
				"Opinions and Observations: Shares views on various topics including politics, social trends, music/film critiques, and everyday life.",
				"Anecdotes and Humor: Relates personal stories, often humorous or embarrassing experiences.",
				"Complaints and Venting: Expresses dissatisfaction with work, technology issues, health problems/hangovers, and poor service.",
			],
			style: [
				"Informal and Conversational: Uses colloquial language, slang ('shit', 'mate', 'boss', 'skint'), and a chatty, direct tone.",
				"Humorous and Self-Deprecating: Frequently employs humor, including sarcasm and jokes often aimed at himself.",
				"Opinionated: Clearly states his opinions, sometimes strongly, on subjects he discusses.",
				"Prone to Corrections: Often sends follow-up messages to correct typos or clarify previous statements.",
				"Uses Emojis/GIFs: Incorporates emojis and mentions sending/using GIFs to add expression.",
				"Reflective: Shares personal feelings about boredom, stress, aging, and life satisfaction (or lack thereof).",
			],
		},
		"Lucy Barnes": {
			summary:
				"Lucy Barnes' messages primarily revolve around social interactions and planning with friends (referred to as Gaz, Mike, Rob, Ian). She discusses arrangements for nights out, Christmas parties, birthdays, and casual meet-ups like walks in the park. Her messages also cover personal updates, such as taking time off work, going on holidays (like Benidorm ), and appointments like dentist visits. She frequently mentions her dog, Chester, and her dog-sitting activities for friends, including looking after Rocky. She actively engages with others' messages, commenting on TV shows (like Breaking Bad, Stranger Things ), events (like the Grand National, boxing ), pet health issues, and sharing photos or reactions.",
			contentThemes: [
				"Social Planning: Coordinating dates, times, and activities for gatherings with friends.",
				"Responses & Reactions: Engaging directly with messages from others, offering opinions, congratulations, or sympathy.",
				"Personal Updates: Sharing information about her availability, holidays, pet care activities, and appointments.",
				"Opinions & Commentary: Expressing views on TV shows, films, events, and sometimes others' choices or situations.",
				"Inquiries: Asking questions to clarify plans or get information.",
				"Expressions of Emotion: Showing enthusiasm, amusement, concern, or agreement, often using emojis.",
			],
			style: [
				"Informal & Friendly: Uses a casual, chatty tone with greetings like 'Hiya' and direct address to individuals.",
				"Expressive & Enthusiastic: Frequently uses multiple exclamation marks and emojis to convey excitement, agreement, or other emotions.",
				"Interactive & Responsive: Directly replies to others' points and asks clarifying questions.",
				"Occasional Corrections: Sometimes sends follow-up messages to correct typos (e.g., Brain !! WTF is Brian!!!!, Competition!!!, *having).",
			],
		},
		"Nicholas Barooah": {
			summary:
				"Nicholas Barooah appears to be a sociable individual interested in technology, gaming, and entertainment (TV/movies). His messages often involve coordinating plans with friends, sharing links, discussing current events (like football or news), and offering opinions on various topics. His communication style is generally informal, conversational, and frequently incorporates humor and emojis. He also discusses personal life aspects like family, work situations, and DIY projects.",
			contentThemes: [
				"Social Coordination: A significant portion of messages involves planning social events, like meeting up for drinks or meals, arranging lifts, and coordinating timings with friends (e.g., Mike, Rob, Gaz).",
				"Technology & Gaming: Frequent discussions about technology, including AI (ChatGPT, Midjourney, Gemini), gadgets (VR headsets, HDMI adapters, smart thermostats, Ring doorbells), software/apps (Kodi, Vercel, Supabase, Flowbite, MUI), computer hardware (CPUs, graphics cards, monitors), gaming (GTA, Andor, The Peripheral, Mr. Robot, Silo, Helldivers 2, Project Zomboid, Left 4 Dead 2, Gauntlet), and troubleshooting technical issues.",
				"TV Shows & Movies: Sharing opinions and recommendations for TV series (Andor, The Peripheral, Mr. Robot, Star Wars, The Last of Us, Silo, Ted, Shogun, 3 Body Problem, Game of Thrones, Red Dwarf, Banshee, Severance, Dark Matter, Killing Eve, Foundation, Adolescence) and movies (Rogue One, The Matrix, Alien Romulus, Roadhouse, Starship Troopers, Wishmaster, Her).",
				"Work & Career: Discussing work situations, job hunting, redundancy, potential startups, and frustrations with work.",
				"Personal Life & Family: Mentioning family members (Yossie, Ollie, mum), health concerns, personal experiences (like burning hand, jet lag, hangovers, DIY projects), financial matters (being broke, mortgage rates, bills, cost of living), and opinions on various topics (football teams, politics, social issues).",
				"Sharing Links: Often shares links to articles (Reddit, Guardian, BBC News, news sites), videos (YouTube), products (Amazon), or websites related to discussions.",
			],
			style: [
				"Direct & To the Point: Communicates in a straightforward manner, especially when coordinating or asking questions.",
				"Opinionated: Expresses clear opinions on various subjects like technology, movies, football, and personal experiences.",
				"Typos & Corrections: Occasionally makes typos and sometimes corrects them in a subsequent message.",
			],
		},
	},
	messagesByMonthAndYear: {
		"2016": {
			"10": 491,
			"11": 130,
			"12": 356,
			"04": 456,
			"05": 668,
			"06": 614,
			"07": 933,
			"08": 776,
			"09": 829,
		},
		"2017": {
			"10": 1477,
			"11": 1341,
			"12": 717,
			"01": 1395,
			"02": 1574,
			"03": 1358,
			"04": 1055,
			"05": 2145,
			"06": 2421,
			"07": 1538,
			"08": 1159,
			"09": 1403,
		},
		"2018": {
			"10": 2167,
			"11": 1659,
			"12": 1350,
			"01": 1271,
			"02": 703,
			"03": 840,
			"04": 636,
			"05": 889,
			"06": 1353,
			"07": 1503,
			"08": 824,
			"09": 1842,
		},
		"2019": {
			"10": 1137,
			"11": 931,
			"12": 1217,
			"01": 1455,
			"02": 1029,
			"03": 1577,
			"04": 1307,
			"05": 1496,
			"06": 1797,
			"07": 1966,
			"08": 1422,
			"09": 1303,
		},
		"2020": {
			"10": 1389,
			"11": 1264,
			"12": 1280,
			"01": 1587,
			"02": 1659,
			"03": 3013,
			"04": 2930,
			"05": 1698,
			"06": 1877,
			"07": 1445,
			"08": 1183,
			"09": 1125,
		},
		"2021": {
			"10": 975,
			"11": 689,
			"12": 831,
			"01": 1474,
			"02": 1244,
			"03": 1693,
			"04": 1339,
			"05": 1314,
			"06": 1385,
			"07": 1333,
			"08": 604,
			"09": 583,
		},
		"2022": {
			"10": 785,
			"11": 1034,
			"12": 1021,
			"01": 770,
			"02": 872,
			"03": 1029,
			"04": 611,
			"05": 1001,
			"06": 867,
			"07": 759,
			"08": 814,
			"09": 1018,
		},
		"2023": {
			"10": 1687,
			"11": 1354,
			"12": 1389,
			"01": 928,
			"02": 453,
			"03": 410,
			"04": 641,
			"05": 511,
			"06": 743,
			"07": 1540,
			"08": 1377,
			"09": 895,
		},
		"2024": {
			"10": 1281,
			"11": 886,
			"12": 1599,
			"01": 1866,
			"02": 1722,
			"03": 2190,
			"04": 1004,
			"05": 1313,
			"06": 1871,
			"07": 1739,
			"08": 1497,
			"09": 1759,
		},
		"2025": {
			"01": 1910,
			"02": 1000,
			"03": 1375,
			"04": 459,
		},
	},
};
